# default base image
ARG BASE_IMAGE="public.ecr.aws/neuron/pytorch-inference-neuronx:2.1.2-neuronx-py310-sdk2.19.1-ubuntu20.04"

FROM $BASE_IMAGE

RUN echo "Base image is $BASE_IMAGE"

# Install some basic utilities
RUN apt-get update && apt-get install git python3 python3-pip -y

### Mount Point ###
# When launching the container, mount the code directory to /app
ARG APP_MOUNT=/app
VOLUME [ ${APP_MOUNT} ]
WORKDIR ${APP_MOUNT}


ENV PIP_EXTRA_INDEX_URL=https://pip.repos.neuron.amazonaws.com
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir fastapi ninja tokenizers pandas && \
    python3 -m pip install sentencepiece transformers==4.36.2 -U && \
    python3 -m pip install transformers-neuronx -U && \
    python3 -m pip install --pre neuronx-cc==2.12.* -U


COPY . /app/vllm

RUN cd /app/vllm && \
    python3 -m pip install -U -r requirements-neuron.txt

ENV VLLM_TARGET_DEVICE=neuron
RUN --mount=type=bind,source=.git,target=.git \
    cd /app/vllm \
    && pip install -v -e . \
    && cd ..

CMD ["/bin/bash"]
